# Default Rooms
from simpleenvs.envs.discrete_rooms.rooms import DiscreteRoomEnvironment
from simpleenvs.envs.discrete_rooms.rooms import DiscreteDefaultTwoRooms
from simpleenvs.envs.discrete_rooms.rooms import DiscreteDefaultSixRooms
from simpleenvs.envs.discrete_rooms.rooms import DiscreteDefaultNineRooms
from simpleenvs.envs.discrete_rooms.rooms import DiscreteXuFourRooms
from simpleenvs.envs.discrete_rooms.rooms import BridgeRoom
from simpleenvs.envs.discrete_rooms.rooms import CageRoom
from simpleenvs.envs.discrete_rooms.rooms import EmptyRoom
from simpleenvs.envs.discrete_rooms.rooms import SmallRooms
from simpleenvs.envs.discrete_rooms.rooms import FourRooms
from simpleenvs.envs.discrete_rooms.rooms import FourRoomsHoles
from simpleenvs.envs.discrete_rooms.rooms import MazeRooms
from simpleenvs.envs.discrete_rooms.rooms import SpiralRoom
from simpleenvs.envs.discrete_rooms.rooms import ParrMaze
from simpleenvs.envs.discrete_rooms.rooms import ParrMiniMaze
from simpleenvs.envs.discrete_rooms.rooms import RameshMaze
from simpleenvs.envs.discrete_rooms.rooms import WidePath
from simpleenvs.envs.discrete_rooms.rooms import BasicRewardRoom
from simpleenvs.envs.discrete_rooms.rooms import DoubleRewardRoom
